env: development

server:
  host: localhost
  port: 8080


auth:
  jwt_secret: "some_secret_key"
  jwt_expiration: 24
  bcrypt_cost: 12

log:
  level: info        
  format: json       
  output: stdout     

video:
  storage_path: "videos"
  max_file_size: 1073741824 # 1GB in bytes
  max_files: 100
  retention_days: 30